defmodule Mix.Tasks.Pulsar.Gen.Button do
  use Pulsar.Generator,
    component: :button,
    example: "mix pulsar.gen.button",
    long_doc: """
    Generates a beautiful, accessible button component with polymorphic rendering

    Creates a fully-featured button component supporting multiple variants, colors,
    sizes, loading states, and smart navigation. Renders as button, link, or div
    elements with proper accessibility and XSS protection.

    ## Example

    ```sh
    mix pulsar.gen.button

    # With custom module namespace
    mix pulsar.gen.button --components-module=MyAppWeb.UI
    ```

    ## Features

    - Polymorphic rendering (button, a, or div elements)
    - Variants: solid, outline, ghost, link
    - Colors: neutral, primary, secondary, success, danger, warning, info
    - Sizes: xs, sm, md, lg, xl
    - Loading states with spinner
    - Phoenix navigation support (navigate, patch, href)
    - XSS protection for href attributes
    - WCAG 2.2 AA accessibility compliance
    - Keyboard navigation for pseudo-buttons

    ## Usage Examples

    ```elixir
    # Basic button
    <.button variant="solid" color="primary">Save Changes</.button>

    # With loading state
    <.button variant="solid" color="success" loading={@saving}>
      Submit Form
    </.button>

    # Navigation button
    <.button variant="outline" navigate={~p"/dashboard"}>
      Go to Dashboard
    </.button>

    # Link variant
    <.button variant="link" color="primary" href="https://example.com">
      Learn More
    </.button>
    ```

    ## Options

    * `--components-module=MODULE` or `-M` - Target module namespace (default: YourAppWeb.Components)
    * `--no-tests` - Skip generating the component's ExUnit smoke test (generated by default)
    """
end
